import { Product } from "./types";
// Định nghĩa interface cho cấu trúc dữ liệu phân trang
interface PaginatedResponse {
  data: Product[];
  pagination: {
    totalItems: number;
    itemsPerPage: number;
    currentPage: number;
    totalPages: number;
  };
  filters: {
    availableColors: string[];
    availableSizes: string[];
    availableSuitability: string[];
    priceRange?: {
      min: number;
      max: number;
    };
  };
}

export const productData: Product[] = [
  // 1-10: Áo thun
  {
    id: "1001",
    name: "Áo thun cotton basic",
    color: ["black", "white", "blue"],
    sizes: ["S", "M", "L", "XL"],
    price: 299000,
    originalPrice: 350000,
    rating: {
      value: 4.6,
      count: 108,
    },
    suitability: ["home", "sport"],
    stock: [
      { size: "S", color: "black", stock: 15 },
      { size: "M", color: "black", stock: 20 },
      { size: "L", color: "black", stock: 18 },
      { size: "XL", color: "black", stock: 10 },
      { size: "S", color: "white", stock: 12 },
      { size: "M", color: "white", stock: 22 },
      { size: "L", color: "white", stock: 16 },
      { size: "XL", color: "white", stock: 8 },
      { size: "S", color: "blue", stock: 14 },
      { size: "M", color: "blue", stock: 19 },
      { size: "L", color: "blue", stock: 17 },
      { size: "XL", color: "blue", stock: 9 },
    ],
    images: [
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den14.webp",
        color: "black",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 20,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den15.webp",
        color: "black",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 20,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den6.webp",
        color: "white",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 22,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den7.webp",
        color: "white",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 22,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/ao-thun-nam-cotton-220gsm-mau-xanh-dam_(1).webp",
        color: "blue",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 19,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/ao-thun-nam-cotton-220gsm-mau-xanh-dam_(2).webp",
        color: "blue",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 19,
      },
    ],
  },
  {
    id: "1002",
    name: "Áo thun premium cotton",
    color: ["black", "white", "blue"],
    sizes: ["S", "M", "L", "XL"],
    price: 349000,
    originalPrice: 399000,
    rating: {
      value: 5,
      count: 100,
    },
    stock: [
      { size: "S", color: "black", stock: 10 },
      { size: "M", color: "black", stock: 15 },
      { size: "L", color: "black", stock: 12 },
      { size: "XL", color: "black", stock: 8 },
      { size: "S", color: "white", stock: 9 },
      { size: "M", color: "white", stock: 16 },
      { size: "L", color: "white", stock: 14 },
      { size: "XL", color: "white", stock: 7 },
      { size: "S", color: "blue", stock: 11 },
      { size: "M", color: "blue", stock: 14 },
      { size: "L", color: "blue", stock: 13 },
      { size: "XL", color: "blue", stock: 9 },
    ],
    images: [
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.xd.6.webp",
        color: "black",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 15,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den14.webp",
        color: "black",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 15,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den7.webp",
        color: "white",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 16,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den6.webp",
        color: "white",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 16,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/ao-thun-nam-cotton-220gsm-mau-xanh-dam_(2).webp",
        color: "blue",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 14,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.xd.12.webp",
        color: "blue",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 14,
      },
    ],
  },
  {
    id: "1003",
    name: "Áo thun thể thao nam",
    color: ["black", "white", "blue"],
    sizes: ["S", "M", "L", "XL"],
    price: 279000,
    originalPrice: 329000,
    rating: {
      value: 3,
      count: 80,
    },
    stock: [
      { size: "S", color: "black", stock: 20 },
      { size: "M", color: "black", stock: 25 },
      { size: "L", color: "black", stock: 18 },
      { size: "XL", color: "black", stock: 15 },
      { size: "S", color: "white", stock: 22 },
      { size: "M", color: "white", stock: 27 },
      { size: "L", color: "white", stock: 20 },
      { size: "XL", color: "white", stock: 17 },
      { size: "S", color: "blue", stock: 21 },
      { size: "M", color: "blue", stock: 26 },
      { size: "L", color: "blue", stock: 19 },
      { size: "XL", color: "blue", stock: 16 },
    ],
    images: [
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den15.webp",
        color: "black",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 25,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den14.webp",
        color: "black",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 25,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.xd.5.jpg",
        color: "white",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 27,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den7.webp",
        color: "white",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 27,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/ao-thun-nam-cotton-220gsm-mau-xanh-dam_(1).webp",
        color: "blue",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 26,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/ao-thun-nam-cotton-220gsm-mau-xanh-dam_(2).webp",
        color: "blue",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 26,
      },
    ],
  },
  {
    id: "1004",
    name: "Áo thun cổ tròn basic",
    color: ["black", "white", "blue"],
    sizes: ["S", "M", "L", "XL"],
    price: 249000,
    originalPrice: 299000,
    rating: {
      value: 4.0,
      count: 110,
    },
    stock: [
      { size: "S", color: "black", stock: 25 },
      { size: "M", color: "black", stock: 30 },
      { size: "L", color: "black", stock: 28 },
      { size: "XL", color: "black", stock: 20 },
      { size: "S", color: "white", stock: 23 },
      { size: "M", color: "white", stock: 32 },
      { size: "L", color: "white", stock: 26 },
      { size: "XL", color: "white", stock: 18 },
      { size: "S", color: "blue", stock: 24 },
      { size: "M", color: "blue", stock: 29 },
      { size: "L", color: "blue", stock: 27 },
      { size: "XL", color: "blue", stock: 19 },
    ],
    images: [
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.xd.6.webp",
        color: "black",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 30,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den15.webp",
        color: "black",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 30,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den6.webp",
        color: "white",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 32,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.xd.5.jpg",
        color: "white",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 32,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.xd.12.webp",
        color: "blue",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 29,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/ao-thun-nam-cotton-220gsm-mau-xanh-dam_(2).webp",
        color: "blue",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 29,
      },
    ],
  },
  {
    id: "1005",
    name: "Áo thun hè chất mát",
    color: ["black", "white", "blue"],
    sizes: ["S", "M", "L", "XL"],
    price: 269000,
    originalPrice: 319000,
    rating: {
      value: 4.0,
      count: 110,
    },
    stock: [
      { size: "S", color: "black", stock: 15 },
      { size: "M", color: "black", stock: 20 },
      { size: "L", color: "black", stock: 18 },
      { size: "XL", color: "black", stock: 12 },
      { size: "S", color: "white", stock: 14 },
      { size: "M", color: "white", stock: 19 },
      { size: "L", color: "white", stock: 17 },
      { size: "XL", color: "white", stock: 11 },
      { size: "S", color: "blue", stock: 16 },
      { size: "M", color: "blue", stock: 21 },
      { size: "L", color: "blue", stock: 19 },
      { size: "XL", color: "blue", stock: 13 },
    ],
    images: [
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den14.webp",
        color: "black",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 20,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.xd.6.webp",
        color: "black",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 20,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den7.webp",
        color: "white",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 19,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den6.webp",
        color: "white",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 19,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/ao-thun-nam-cotton-220gsm-mau-xanh-dam_(1).webp",
        color: "blue",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 21,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.xd.12.webp",
        color: "blue",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 21,
      },
    ],
  },
  {
    id: "1006",
    name: "Áo thun cao cấp",
    color: ["black", "white", "blue"],
    sizes: ["S", "M", "L", "XL"],
    price: 399000,
    originalPrice: 499000,
    rating: {
      value: 4.0,
      count: 110,
    },
    stock: [
      { size: "S", color: "black", stock: 8 },
      { size: "M", color: "black", stock: 12 },
      { size: "L", color: "black", stock: 10 },
      { size: "XL", color: "black", stock: 6 },
      { size: "S", color: "white", stock: 7 },
      { size: "M", color: "white", stock: 11 },
      { size: "L", color: "white", stock: 9 },
      { size: "XL", color: "white", stock: 5 },
      { size: "S", color: "blue", stock: 9 },
      { size: "M", color: "blue", stock: 13 },
      { size: "L", color: "blue", stock: 11 },
      { size: "XL", color: "blue", stock: 7 },
    ],
    images: [
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den15.webp",
        color: "black",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 12,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den14.webp",
        color: "black",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 12,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.xd.5.jpg",
        color: "white",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 11,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den6.webp",
        color: "white",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 11,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/ao-thun-nam-cotton-220gsm-mau-xanh-dam_(2).webp",
        color: "blue",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 13,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/ao-thun-nam-cotton-220gsm-mau-xanh-dam_(1).webp",
        color: "blue",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 13,
      },
    ],
  },
  {
    id: "1007",
    name: "Áo thun oversize",
    color: ["black", "white", "blue"],
    sizes: ["S", "M", "L", "XL"],
    price: 289000,
    originalPrice: 339000,
    rating: {
      value: 4.0,
      count: 110,
    },
    stock: [
      { size: "S", color: "black", stock: 18 },
      { size: "M", color: "black", stock: 22 },
      { size: "L", color: "black", stock: 20 },
      { size: "XL", color: "black", stock: 16 },
      { size: "S", color: "white", stock: 17 },
      { size: "M", color: "white", stock: 21 },
      { size: "L", color: "white", stock: 19 },
      { size: "XL", color: "white", stock: 15 },
      { size: "S", color: "blue", stock: 19 },
      { size: "M", color: "blue", stock: 23 },
      { size: "L", color: "blue", stock: 21 },
      { size: "XL", color: "blue", stock: 17 },
    ],
    images: [
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.xd.6.webp",
        color: "black",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 22,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den15.webp",
        color: "black",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 22,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den7.webp",
        color: "white",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 21,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den6.webp",
        color: "white",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 21,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.xd.12.webp",
        color: "blue",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 23,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/ao-thun-nam-cotton-220gsm-mau-xanh-dam_(1).webp",
        color: "blue",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 23,
      },
    ],
  },
  {
    id: "1008",
    name: "Áo thun nam slim fit",
    color: ["black", "white", "blue"],
    sizes: ["S", "M", "L", "XL"],
    price: 279000,
    originalPrice: 339000,
    rating: {
      value: 4.0,
      count: 110,
    },
    stock: [
      { size: "S", color: "black", stock: 22 },
      { size: "M", color: "black", stock: 28 },
      { size: "L", color: "black", stock: 24 },
      { size: "XL", color: "black", stock: 18 },
      { size: "S", color: "white", stock: 20 },
      { size: "M", color: "white", stock: 26 },
      { size: "L", color: "white", stock: 22 },
      { size: "XL", color: "white", stock: 16 },
      { size: "S", color: "blue", stock: 21 },
      { size: "M", color: "blue", stock: 27 },
      { size: "L", color: "blue", stock: 23 },
      { size: "XL", color: "blue", stock: 17 },
    ],
    images: [
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den14.webp",
        color: "black",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 28,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.xd.6.webp",
        color: "black",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 28,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den6.webp",
        color: "white",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 26,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.xd.5.jpg",
        color: "white",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 26,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/ao-thun-nam-cotton-220gsm-mau-xanh-dam_(1).webp",
        color: "blue",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 27,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/ao-thun-nam-cotton-220gsm-mau-xanh-dam_(2).webp",
        color: "blue",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 27,
      },
    ],
  },
  {
    id: "1009",
    name: "Áo thun nam cổ trụ",
    color: ["black", "white", "blue"],
    sizes: ["S", "M", "L", "XL"],
    price: 319000,
    originalPrice: 369000,
    rating: {
      value: 4.0,
      count: 110,
    },
    stock: [
      { size: "S", color: "black", stock: 14 },
      { size: "M", color: "black", stock: 18 },
      { size: "L", color: "black", stock: 16 },
      { size: "XL", color: "black", stock: 12 },
      { size: "S", color: "white", stock: 15 },
      { size: "M", color: "white", stock: 19 },
      { size: "L", color: "white", stock: 17 },
      { size: "XL", color: "white", stock: 13 },
      { size: "S", color: "blue", stock: 13 },
      { size: "M", color: "blue", stock: 17 },
      { size: "L", color: "blue", stock: 15 },
      { size: "XL", color: "blue", stock: 11 },
    ],
    images: [
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den15.webp",
        color: "black",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 18,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den14.webp",
        color: "black",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 18,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den7.webp",
        color: "white",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 19,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.xd.5.jpg",
        color: "white",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 19,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/ao-thun-nam-cotton-220gsm-mau-xanh-dam_(2).webp",
        color: "blue",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 17,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.xd.12.webp",
        color: "blue",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 17,
      },
    ],
  },
  {
    id: "1010",
    name: "Áo thun nam chất đẹp",
    color: ["black", "white", "blue"],
    sizes: ["S", "M", "L", "XL"],
    price: 259000,
    originalPrice: 309000,
    rating: {
      value: 4.0,
      count: 110,
    },
    stock: [
      { size: "S", color: "black", stock: 24 },
      { size: "M", color: "black", stock: 30 },
      { size: "L", color: "black", stock: 26 },
      { size: "XL", color: "black", stock: 22 },
      { size: "S", color: "white", stock: 25 },
      { size: "M", color: "white", stock: 31 },
      { size: "L", color: "white", stock: 27 },
      { size: "XL", color: "white", stock: 23 },
      { size: "S", color: "blue", stock: 23 },
      { size: "M", color: "blue", stock: 29 },
      { size: "L", color: "blue", stock: 25 },
      { size: "XL", color: "blue", stock: 21 },
    ],
    images: [
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.xd.6.webp",
        color: "black",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 30,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den15.webp",
        color: "black",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 30,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den6.webp",
        color: "white",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 31,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den7.webp",
        color: "white",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 31,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/ao-thun-nam-cotton-220gsm-mau-xanh-dam_(1).webp",
        color: "blue",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 29,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.xd.12.webp",
        color: "blue",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 29,
      },
    ],
  },

  // 11-20: Áo polo
  {
    id: "2001",
    name: "Áo polo nam basic",
    color: ["black", "white", "blue"],
    sizes: ["S", "M", "L", "XL"],
    price: 349000,
    originalPrice: 399000,
    rating: {
      value: 4.0,
      count: 110,
    },
    stock: [
      { size: "S", color: "black", stock: 15 },
      { size: "M", color: "black", stock: 20 },
      { size: "L", color: "black", stock: 18 },
      { size: "XL", color: "black", stock: 12 },
      { size: "S", color: "white", stock: 14 },
      { size: "M", color: "white", stock: 19 },
      { size: "L", color: "white", stock: 17 },
      { size: "XL", color: "white", stock: 11 },
      { size: "S", color: "blue", stock: 16 },
      { size: "M", color: "blue", stock: 21 },
      { size: "L", color: "blue", stock: 19 },
      { size: "XL", color: "blue", stock: 13 },
    ],
    images: [
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den14.webp",
        color: "black",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 20,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den15.webp",
        color: "black",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 20,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den7.webp",
        color: "white",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 19,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den6.webp",
        color: "white",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 19,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/ao-thun-nam-cotton-220gsm-mau-xanh-dam_(2).webp",
        color: "blue",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 21,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/ao-thun-nam-cotton-220gsm-mau-xanh-dam_(1).webp",
        color: "blue",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 21,
      },
    ],
  },

  // Tiếp tục với các sản phẩm từ 2002-3030...
  // (Tiếp thêm 20 sản phẩm với cấu trúc tương tự nhưng thay đổi tên, giá, số lượng tồn kho)

  {
    id: "2002",
    name: "Áo polo nam thể thao",
    color: ["black", "white", "blue"],
    sizes: ["S", "M", "L", "XL"],
    price: 329000,
    originalPrice: 379000,
    rating: {
      value: 4.0,
      count: 110,
    },
    stock: [
      { size: "S", color: "black", stock: 12 },
      { size: "M", color: "black", stock: 18 },
      { size: "L", color: "black", stock: 15 },
      { size: "XL", color: "black", stock: 10 },
      { size: "S", color: "white", stock: 13 },
      { size: "M", color: "white", stock: 19 },
      { size: "L", color: "white", stock: 16 },
      { size: "XL", color: "white", stock: 11 },
      { size: "S", color: "blue", stock: 14 },
      { size: "M", color: "blue", stock: 20 },
      { size: "L", color: "blue", stock: 17 },
      { size: "XL", color: "blue", stock: 12 },
    ],
    images: [
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.xd.6.webp",
        color: "black",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 18,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den14.webp",
        color: "black",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 18,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.xd.5.jpg",
        color: "white",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 19,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den6.webp",
        color: "white",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 19,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.xd.12.webp",
        color: "blue",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 20,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/ao-thun-nam-cotton-220gsm-mau-xanh-dam_(2).webp",
        color: "blue",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 20,
      },
    ],
  },

  // 21-30: Áo sơ mi, hoodie, v.v.
  // Thêm 10 sản phẩm khác...
  {
    id: "3003",
    name: "Áo polo nam thể thao",
    color: ["black", "white", "blue"],
    sizes: ["S", "M", "L", "XL"],
    price: 329000,
    originalPrice: 379000,
    rating: {
      value: 4.0,
      count: 110,
    },
    stock: [
      { size: "S", color: "black", stock: 12 },
      { size: "M", color: "black", stock: 18 },
      { size: "L", color: "black", stock: 15 },
      { size: "XL", color: "black", stock: 10 },
      { size: "S", color: "white", stock: 13 },
      { size: "M", color: "white", stock: 19 },
      { size: "L", color: "white", stock: 16 },
      { size: "XL", color: "white", stock: 11 },
      { size: "S", color: "blue", stock: 14 },
      { size: "M", color: "blue", stock: 20 },
      { size: "L", color: "blue", stock: 17 },
      { size: "XL", color: "blue", stock: 12 },
    ],
    images: [
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.xd.6.webp",
        color: "black",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 18,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den14.webp",
        color: "black",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 18,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.xd.5.jpg",
        color: "white",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 19,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.den6.webp",
        color: "white",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 19,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/AT.220.xd.12.webp",
        color: "blue",
        size: "M",
        isFront: true,
        isProductOnly: false,
        stock: 20,
      },
      {
        src: "https://shop-online-images.s3.ap-southeast-2.amazonaws.com/ao-thun-nam-cotton/ao-thun-nam-cotton-220gsm-mau-xanh-dam_(2).webp",
        color: "blue",
        size: "M",
        isFront: false,
        isProductOnly: true,
        stock: 20,
      },
    ],
  },
  // Các sản phẩm còn lại - tổng 30 sản phẩm
];
// Export mockData với định dạng phân trang mà API thường trả về
export const mockData: PaginatedResponse = {
  data: productData,
  pagination: {
    totalItems: productData.length,
    itemsPerPage: 12,
    currentPage: 1,
    totalPages: Math.ceil(productData.length / 12),
  },
  filters: {
    availableColors: [
      "black",
      "white",
      "blue",
      "red",
      "green",
      "yellow",
      "purple",
      "gray",
    ],
    availableSizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL"],
    priceRange: {
      min: 249000,
      max: 399000,
    },
    availableSuitability: ["home", "daily", "sport"],
  },
};

// Hàm trả về dữ liệu phân trang theo trang được yêu cầu
export function getMockPaginatedData(
  page: number,
  limit: number
): PaginatedResponse {
  const startIndex = (page - 1) * limit;
  const endIndex = Math.min(startIndex + limit, productData.length);

  return {
    data: productData.slice(startIndex, endIndex),
    pagination: {
      totalItems: productData.length,
      itemsPerPage: limit,
      currentPage: page,
      totalPages: Math.ceil(productData.length / limit),
    },
    filters: mockData.filters,
  };
}

export function getMockProductById(id: string): Product | null {
  return productData.find((product) => product.id === id) || null;
}
